---
title: "Practical Machine Learning Course Project"
author: "De Chen"
date: "3/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)
library(ggplot2)
library(caret)
library(dplyr)
library(data.table)
```


```{r download data, include=FALSE}
setwd("/Users/DE/Desktop/Coursera/Machine Learning/Course Project")
if (!file.exists("training.csv")) {
download.file(
    url = "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv",
    destfile = "training.csv")}
if (!file.exists("test.csv")) {
download.file(
    url = "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv",
    destfile = "test.csv")}
train = read.csv("training.csv", na.strings = c("NA", ""))
test = read.csv("test.csv", na.strings = c("NA", ""))                     
```

```{r data manipulation, include=FALSE}
mdata = train[,-1]
test = test[,-1]
set.seed(1013)
train_index = createDataPartition(y = mdata$classe, p = 0.6, list = F)
training = mdata[train_index,]
validation = mdata[-train_index,]
```

```{r eda}
missing_rows = sapply(training, function(x){sum(is.na(x)|is.nan(x))/length(x)})
missing_rows[missing_rows < 0.5]
candidate_var = names(missing_rows[missing_rows < 0.5])
nums = sapply(training[,candidate_var], is.numeric)
M = abs(cor(training[,names(nums[nums==TRUE])]))
findCorrelation(M, cutoff = 0.8, verbose = F, names = T, exact = T)
```